- hosts: gitlab
  roles:
    - { role: andrewrothstein.git, tags: ["git"] }
    - { role: sourcejedi.etckeeper, tags: ["etckeeper"] }
    - { role: haxorof.docker_ce, tags: ["docker"] }
    - { role: gitlab-ce, tags: ["gitlab-ce"] }

- hosts: empty
  roles:
    - { role: andrewrothstein.git, tags: ["git"] }
    - { role: sourcejedi.etckeeper, tags: ["etckeeper"] }
    - { role: haxorof.docker_ce, tags: ["docker"] }

- hosts: pavics
  roles:
    - { role: andrewrothstein.git, tags: ["git"] }
    - { role: sourcejedi.etckeeper, tags: ["etckeeper"] }
    - { role: haxorof.docker_ce, tags: ["docker"] }
